<?php
/**
 * Acpv1instructionsinstructionIdcredentialsOrderInformationItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Acpv1instructionsinstructionIdcredentialsOrderInformationItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description Acpv1instructionsinstructionIdcredentialsOrderInformationItems
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Acpv1instructionsinstructionIdcredentialsOrderInformationItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Acpv1instructionsinstructionIdcredentialsOrderInformationItems"
     */
    public function testAcpv1instructionsinstructionIdcredentialsOrderInformationItems()
    {
    }

    /**
     * Test attribute "productSku"
     */
    public function testPropertyProductSku()
    {
    }

    /**
     * Test attribute "productName"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "unitPriceCurrency"
     */
    public function testPropertyUnitPriceCurrency()
    {
    }

    /**
     * Test attribute "amountDetail"
     */
    public function testPropertyAmountDetail()
    {
    }

    /**
     * Test attribute "productUrl"
     */
    public function testPropertyProductUrl()
    {
    }

    /**
     * Test attribute "policies"
     */
    public function testPropertyPolicies()
    {
    }

    /**
     * Test attribute "additionalInfo"
     */
    public function testPropertyAdditionalInfo()
    {
    }
}
