<?php
/**
 * Acpv1tokensEnrollmentReferenceDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Acpv1tokensEnrollmentReferenceDataTest Class Doc Comment
 *
 * @category    Class */
// * @description Enrollment Reference Data. Links the enrollment to an existing token reference.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Acpv1tokensEnrollmentReferenceDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Acpv1tokensEnrollmentReferenceData"
     */
    public function testAcpv1tokensEnrollmentReferenceData()
    {
    }

    /**
     * Test attribute "enrollmentReferenceType"
     */
    public function testPropertyEnrollmentReferenceType()
    {
    }

    /**
     * Test attribute "enrollmentReferenceProvider"
     */
    public function testPropertyEnrollmentReferenceProvider()
    {
    }
}
