<?php
/**
 * AgentRegistrationResponse201Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * AgentRegistrationResponse201Test Class Doc Comment
 *
 * @category    Class */
// * @description Response object for a registered agent, including its associated public keys.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgentRegistrationResponse201Test extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AgentRegistrationResponse201"
     */
    public function testAgentRegistrationResponse201()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "contactEmail"
     */
    public function testPropertyContactEmail()
    {
    }

    /**
     * Test attribute "tokenRequestorId"
     */
    public function testPropertyTokenRequestorId()
    {
    }

    /**
     * Test attribute "agentType"
     */
    public function testPropertyAgentType()
    {
    }

    /**
     * Test attribute "agentMetadata"
     */
    public function testPropertyAgentMetadata()
    {
    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "keys"
     */
    public function testPropertyKeys()
    {
    }
}
