<?php
/**
 * AgenticCardEnrollmentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * AgenticCardEnrollmentRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description AgenticCardEnrollmentRequest
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgenticCardEnrollmentRequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AgenticCardEnrollmentRequest"
     */
    public function testAgenticCardEnrollmentRequest()
    {
    }

    /**
     * Test attribute "clientCorrelationId"
     */
    public function testPropertyClientCorrelationId()
    {
    }

    /**
     * Test attribute "deviceInformation"
     */
    public function testPropertyDeviceInformation()
    {
    }

    /**
     * Test attribute "buyerInformation"
     */
    public function testPropertyBuyerInformation()
    {
    }

    /**
     * Test attribute "billTo"
     */
    public function testPropertyBillTo()
    {
    }

    /**
     * Test attribute "consumerIdentity"
     */
    public function testPropertyConsumerIdentity()
    {
    }

    /**
     * Test attribute "paymentInformation"
     */
    public function testPropertyPaymentInformation()
    {
    }

    /**
     * Test attribute "enrollmentReferenceData"
     */
    public function testPropertyEnrollmentReferenceData()
    {
    }

    /**
     * Test attribute "assuranceData"
     */
    public function testPropertyAssuranceData()
    {
    }

    /**
     * Test attribute "consentData"
     */
    public function testPropertyConsentData()
    {
    }
}
