<?php
/**
 * BoardingBusinessInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * BoardingBusinessInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description BoardingBusinessInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BoardingBusinessInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BoardingBusinessInformation"
     */
    public function testBoardingBusinessInformation()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "localizedNames"
     */
    public function testPropertyLocalizedNames()
    {
    }

    /**
     * Test attribute "doingBusinessAs"
     */
    public function testPropertyDoingBusinessAs()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "timeZone"
     */
    public function testPropertyTimeZone()
    {
    }

    /**
     * Test attribute "websiteUrl"
     */
    public function testPropertyWebsiteUrl()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "taxId"
     */
    public function testPropertyTaxId()
    {
    }

    /**
     * Test attribute "phoneNumber"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "businessContact"
     */
    public function testPropertyBusinessContact()
    {
    }

    /**
     * Test attribute "technicalContact"
     */
    public function testPropertyTechnicalContact()
    {
    }

    /**
     * Test attribute "emergencyContact"
     */
    public function testPropertyEmergencyContact()
    {
    }

    /**
     * Test attribute "merchantCategoryCode"
     */
    public function testPropertyMerchantCategoryCode()
    {
    }
}
