<?php
/**
 * BoardingAcquirerDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * BoardingAcquirerDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description Contains the specific configuration details for an acquirer.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BoardingAcquirerDetailsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BoardingAcquirerDetails"
     */
    public function testBoardingAcquirerDetails()
    {
    }

    /**
     * Test attribute "acquirerAccountId"
     */
    public function testPropertyAcquirerAccountId()
    {
    }

    /**
     * Test attribute "summerBonusStartDate"
     */
    public function testPropertySummerBonusStartDate()
    {
    }

    /**
     * Test attribute "summerBonusEndDate"
     */
    public function testPropertySummerBonusEndDate()
    {
    }

    /**
     * Test attribute "summerBonusMonth"
     */
    public function testPropertySummerBonusMonth()
    {
    }

    /**
     * Test attribute "winterBonusStartDate"
     */
    public function testPropertyWinterBonusStartDate()
    {
    }

    /**
     * Test attribute "winterBonusEndDate"
     */
    public function testPropertyWinterBonusEndDate()
    {
    }

    /**
     * Test attribute "winterBonusMonth"
     */
    public function testPropertyWinterBonusMonth()
    {
    }

    /**
     * Test attribute "numberOfInstallments"
     */
    public function testPropertyNumberOfInstallments()
    {
    }

    /**
     * Test attribute "paymentModes"
     */
    public function testPropertyPaymentModes()
    {
    }

    /**
     * Test attribute "numberOfInstallmentPayments"
     */
    public function testPropertyNumberOfInstallmentPayments()
    {
    }

    /**
     * Test attribute "numberOfIntegratedInstallments"
     */
    public function testPropertyNumberOfIntegratedInstallments()
    {
    }

    /**
     * Test attribute "numberOfBonusPayments"
     */
    public function testPropertyNumberOfBonusPayments()
    {
    }

    /**
     * Test attribute "centerName"
     */
    public function testPropertyCenterName()
    {
    }

    /**
     * Test attribute "fbnIdentificationFlag"
     */
    public function testPropertyFbnIdentificationFlag()
    {
    }

    /**
     * Test attribute "retailSupported"
     */
    public function testPropertyRetailSupported()
    {
    }

    /**
     * Test attribute "paymentOptions"
     */
    public function testPropertyPaymentOptions()
    {
    }
}
