<?php
/**
 * DefaultPaymentInstrumentCardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * DefaultPaymentInstrumentCardTest Class Doc Comment
 *
 * @category    Class */
// * @description DefaultPaymentInstrumentCard
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DefaultPaymentInstrumentCardTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DefaultPaymentInstrumentCard"
     */
    public function testDefaultPaymentInstrumentCard()
    {
    }

    /**
     * Test attribute "expirationMonth"
     */
    public function testPropertyExpirationMonth()
    {
    }

    /**
     * Test attribute "expirationYear"
     */
    public function testPropertyExpirationYear()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "issueNumber"
     */
    public function testPropertyIssueNumber()
    {
    }

    /**
     * Test attribute "startMonth"
     */
    public function testPropertyStartMonth()
    {
    }

    /**
     * Test attribute "startYear"
     */
    public function testPropertyStartYear()
    {
    }

    /**
     * Test attribute "useAs"
     */
    public function testPropertyUseAs()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "tokenizedInformation"
     */
    public function testPropertyTokenizedInformation()
    {
    }
}
