<?php
/**
 * GetSubscriptionsPaymentsResponseSubscriptionPaymentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * GetSubscriptionsPaymentsResponseSubscriptionPaymentTest Class Doc Comment
 *
 * @category    Class */
// * @description GetSubscriptionsPaymentsResponseSubscriptionPayment
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetSubscriptionsPaymentsResponseSubscriptionPaymentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetSubscriptionsPaymentsResponseSubscriptionPayment"
     */
    public function testGetSubscriptionsPaymentsResponseSubscriptionPayment()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "transactionID"
     */
    public function testPropertyTransactionID()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "billingStartDate"
     */
    public function testPropertyBillingStartDate()
    {
    }

    /**
     * Test attribute "billingEndDate"
     */
    public function testPropertyBillingEndDate()
    {
    }

    /**
     * Test attribute "billingCycle"
     */
    public function testPropertyBillingCycle()
    {
    }

    /**
     * Test attribute "paymentNumber"
     */
    public function testPropertyPaymentNumber()
    {
    }

    /**
     * Test attribute "billingAmount"
     */
    public function testPropertyBillingAmount()
    {
    }

    /**
     * Test attribute "setupFee"
     */
    public function testPropertySetupFee()
    {
    }

    /**
     * Test attribute "surchargeAmount"
     */
    public function testPropertySurchargeAmount()
    {
    }

    /**
     * Test attribute "surchargeDescription"
     */
    public function testPropertySurchargeDescription()
    {
    }

    /**
     * Test attribute "modifiable"
     */
    public function testPropertyModifiable()
    {
    }
}
