<?php
/**
 * IccLineItemPoliciesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * IccLineItemPoliciesTest Class Doc Comment
 *
 * @category    Class */
// * @description Policies related to the item.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IccLineItemPoliciesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IccLineItemPolicies"
     */
    public function testIccLineItemPolicies()
    {
    }

    /**
     * Test attribute "termsAndConditions"
     */
    public function testPropertyTermsAndConditions()
    {
    }

    /**
     * Test attribute "cancellationPolicy"
     */
    public function testPropertyCancellationPolicy()
    {
    }

    /**
     * Test attribute "refundPolicy"
     */
    public function testPropertyRefundPolicy()
    {
    }

    /**
     * Test attribute "disputePolicy"
     */
    public function testPropertyDisputePolicy()
    {
    }

    /**
     * Test attribute "shippingPolicy"
     */
    public function testPropertyShippingPolicy()
    {
    }

    /**
     * Test attribute "discountAndPromotions"
     */
    public function testPropertyDiscountAndPromotions()
    {
    }

    /**
     * Test attribute "propertyName"
     */
    public function testPropertyPropertyName()
    {
    }
}
