<?php
/**
 * Iccv1tokensAssuranceDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iccv1tokensAssuranceDataTest Class Doc Comment
 *
 * @category    Class */
// * @description Assurance data. Contains identity verification details that prove the consumer or device has been authenticated before the payment operation.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iccv1tokensAssuranceDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Iccv1tokensAssuranceData"
     */
    public function testIccv1tokensAssuranceData()
    {
    }

    /**
     * Test attribute "verificationType"
     */
    public function testPropertyVerificationType()
    {
    }

    /**
     * Test attribute "verificationEntity"
     */
    public function testPropertyVerificationEntity()
    {
    }

    /**
     * Test attribute "verificationEvents"
     */
    public function testPropertyVerificationEvents()
    {
    }

    /**
     * Test attribute "verificationMethod"
     */
    public function testPropertyVerificationMethod()
    {
    }

    /**
     * Test attribute "verificationResults"
     */
    public function testPropertyVerificationResults()
    {
    }

    /**
     * Test attribute "verificationTimestamp"
     */
    public function testPropertyVerificationTimestamp()
    {
    }

    /**
     * Test attribute "authenticationContext"
     */
    public function testPropertyAuthenticationContext()
    {
    }

    /**
     * Test attribute "authenticatedIdentities"
     */
    public function testPropertyAuthenticatedIdentities()
    {
    }

    /**
     * Test attribute "additionalData"
     */
    public function testPropertyAdditionalData()
    {
    }
}
