<?php
/**
 * Iccv1instructionsMandatesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iccv1instructionsMandatesTest Class Doc Comment
 *
 * @category    Class */
// * @description Mandate data. Defines the consumer&#39;s spending authorization for a purchase intent, including merchant preferences, amount limits, and product details.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iccv1instructionsMandatesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Iccv1instructionsMandates"
     */
    public function testIccv1instructionsMandates()
    {
    }

    /**
     * Test attribute "mandateId"
     */
    public function testPropertyMandateId()
    {
    }

    /**
     * Test attribute "preferredMerchantName"
     */
    public function testPropertyPreferredMerchantName()
    {
    }

    /**
     * Test attribute "merchantCategory"
     */
    public function testPropertyMerchantCategory()
    {
    }

    /**
     * Test attribute "merchantCategoryCode"
     */
    public function testPropertyMerchantCategoryCode()
    {
    }

    /**
     * Test attribute "declineThreshold"
     */
    public function testPropertyDeclineThreshold()
    {
    }

    /**
     * Test attribute "recurringPaymentInformation"
     */
    public function testPropertyRecurringPaymentInformation()
    {
    }

    /**
     * Test attribute "effectiveUntilTime"
     */
    public function testPropertyEffectiveUntilTime()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }
}
