<?php
/**
 * Iccv1instructionsinstructionIdconfirmationsProcessorInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iccv1instructionsinstructionIdconfirmationsProcessorInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Payment/Transaction Confirmation Data provided by the payment processor/acquirer.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iccv1instructionsinstructionIdconfirmationsProcessorInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Iccv1instructionsinstructionIdconfirmationsProcessorInformation"
     */
    public function testIccv1instructionsinstructionIdconfirmationsProcessorInformation()
    {
    }

    /**
     * Test attribute "dynamicDataId"
     */
    public function testPropertyDynamicDataId()
    {
    }

    /**
     * Test attribute "transactionType"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "transactionStatus"
     */
    public function testPropertyTransactionStatus()
    {
    }

    /**
     * Test attribute "responseCode"
     */
    public function testPropertyResponseCode()
    {
    }

    /**
     * Test attribute "transactionTimestamp"
     */
    public function testPropertyTransactionTimestamp()
    {
    }

    /**
     * Test attribute "approvalCode"
     */
    public function testPropertyApprovalCode()
    {
    }

    /**
     * Test attribute "retrievalReferenceNumber"
     */
    public function testPropertyRetrievalReferenceNumber()
    {
    }

    /**
     * Test attribute "systemTraceAuditNumber"
     */
    public function testPropertySystemTraceAuditNumber()
    {
    }

    /**
     * Test attribute "acquirerReferenceNumber"
     */
    public function testPropertyAcquirerReferenceNumber()
    {
    }

    /**
     * Test attribute "amountDetail"
     */
    public function testPropertyAmountDetail()
    {
    }

    /**
     * Test attribute "entryMode"
     */
    public function testPropertyEntryMode()
    {
    }

    /**
     * Test attribute "paymentInstrument"
     */
    public function testPropertyPaymentInstrument()
    {
    }
}
