<?php
/**
 * Iccv1tokensDeviceInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iccv1tokensDeviceInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Device and Application instance data. Identifies the device and application from which the consumer is making the payment request.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iccv1tokensDeviceInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Iccv1tokensDeviceInformation"
     */
    public function testIccv1tokensDeviceInformation()
    {
    }

    /**
     * Test attribute "userAgent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "applicationName"
     */
    public function testPropertyApplicationName()
    {
    }

    /**
     * Test attribute "fingerprintSessionId"
     */
    public function testPropertyFingerprintSessionId()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "deviceData"
     */
    public function testPropertyDeviceData()
    {
    }

    /**
     * Test attribute "ipAddress"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "clientDeviceId"
     */
    public function testPropertyClientDeviceId()
    {
    }
}
