<?php
/**
 * Iccv1mppcredentialsChallengeEncryptionJwkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iccv1mppcredentialsChallengeEncryptionJwkTest Class Doc Comment
 *
 * @category    Class */
// * @description Merchant RSA public encryption key as a JSON Web Key (JWK,  RFC 7517). Must be RSA (kty&#x3D;RSA), alg&#x3D;RSA-OAEP-256, use&#x3D;enc. Used to encrypt the token payload using RSA-OAEP with SHA-256 per MPP spec Section 7.4.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iccv1mppcredentialsChallengeEncryptionJwkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Iccv1mppcredentialsChallengeEncryptionJwk"
     */
    public function testIccv1mppcredentialsChallengeEncryptionJwk()
    {
    }

    /**
     * Test attribute "kty"
     */
    public function testPropertyKty()
    {
    }

    /**
     * Test attribute "kid"
     */
    public function testPropertyKid()
    {
    }

    /**
     * Test attribute "use"
     */
    public function testPropertyUse()
    {
    }

    /**
     * Test attribute "alg"
     */
    public function testPropertyAlg()
    {
    }

    /**
     * Test attribute "n"
     */
    public function testPropertyN()
    {
    }

    /**
     * Test attribute "e"
     */
    public function testPropertyE()
    {
    }
}
