<?php
/**
 * Iccv1tokensConsumerIdentityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iccv1tokensConsumerIdentityTest Class Doc Comment
 *
 * @category    Class */
// * @description Consumer Identity data. Identifies the consumer using an email address or phone number.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iccv1tokensConsumerIdentityTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Iccv1tokensConsumerIdentity"
     */
    public function testIccv1tokensConsumerIdentity()
    {
    }

    /**
     * Test attribute "identityType"
     */
    public function testPropertyIdentityType()
    {
    }

    /**
     * Test attribute "identityValue"
     */
    public function testPropertyIdentityValue()
    {
    }

    /**
     * Test attribute "identityProvider"
     */
    public function testPropertyIdentityProvider()
    {
    }

    /**
     * Test attribute "identityProviderUrl"
     */
    public function testPropertyIdentityProviderUrl()
    {
    }
}
