<?php
/**
 * InlineResponse2014SetupsRiskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InlineResponse2014SetupsRiskTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2014SetupsRisk
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2014SetupsRiskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2014SetupsRisk"
     */
    public function testInlineResponse2014SetupsRisk()
    {
    }

    /**
     * Test attribute "fraudManagementEssentials"
     */
    public function testPropertyFraudManagementEssentials()
    {
    }

    /**
     * Test attribute "decisionManager"
     */
    public function testPropertyDecisionManager()
    {
    }

    /**
     * Test attribute "enhancedAuthentication"
     */
    public function testPropertyEnhancedAuthentication()
    {
    }
}
