<?php
/**
 * InlineResponse20014Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InlineResponse20014Test Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse20014
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20014Test extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20014"
     */
    public function testInlineResponse20014()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "reportCreatedDate"
     */
    public function testPropertyReportCreatedDate()
    {
    }

    /**
     * Test attribute "batchId"
     */
    public function testPropertyBatchId()
    {
    }

    /**
     * Test attribute "batchSource"
     */
    public function testPropertyBatchSource()
    {
    }

    /**
     * Test attribute "batchCaEndpoints"
     */
    public function testPropertyBatchCaEndpoints()
    {
    }

    /**
     * Test attribute "batchCreatedDate"
     */
    public function testPropertyBatchCreatedDate()
    {
    }

    /**
     * Test attribute "merchantReference"
     */
    public function testPropertyMerchantReference()
    {
    }

    /**
     * Test attribute "totals"
     */
    public function testPropertyTotals()
    {
    }

    /**
     * Test attribute "billing"
     */
    public function testPropertyBilling()
    {
    }

    /**
     * Test attribute "records"
     */
    public function testPropertyRecords()
    {
    }
}
