<?php
/**
 * InlineResponse20019Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InlineResponse20019Test Class Doc Comment
 *
 * @category    Class */
// * @description Result of a product feed ingestion request.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20019Test extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20019"
     */
    public function testInlineResponse20019()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "feedId"
     */
    public function testPropertyFeedId()
    {
    }

    /**
     * Test attribute "totalSubmitted"
     */
    public function testPropertyTotalSubmitted()
    {
    }

    /**
     * Test attribute "successCount"
     */
    public function testPropertySuccessCount()
    {
    }

    /**
     * Test attribute "failedCount"
     */
    public function testPropertyFailedCount()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }

    /**
     * Test attribute "ingestedAt"
     */
    public function testPropertyIngestedAt()
    {
    }

    /**
     * Test attribute "forwardedToAgent"
     */
    public function testPropertyForwardedToAgent()
    {
    }

    /**
     * Test attribute "agentEndpoint"
     */
    public function testPropertyAgentEndpoint()
    {
    }

    /**
     * Test attribute "forwardedToUcpAgent"
     */
    public function testPropertyForwardedToUcpAgent()
    {
    }

    /**
     * Test attribute "googleMerchant"
     */
    public function testPropertyGoogleMerchant()
    {
    }
}
