<?php
/**
 * InlineResponse2014OrderInformationAmountDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InlineResponse2014OrderInformationAmountDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2014OrderInformationAmountDetails
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2014OrderInformationAmountDetailsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2014OrderInformationAmountDetails"
     */
    public function testInlineResponse2014OrderInformationAmountDetails()
    {
    }

    /**
     * Test attribute "markupRate"
     */
    public function testPropertyMarkupRate()
    {
    }

    /**
     * Test attribute "exchangeRate"
     */
    public function testPropertyExchangeRate()
    {
    }

    /**
     * Test attribute "originalAmount"
     */
    public function testPropertyOriginalAmount()
    {
    }

    /**
     * Test attribute "destinationAmount"
     */
    public function testPropertyDestinationAmount()
    {
    }

    /**
     * Test attribute "originalAmountWithoutMarkup"
     */
    public function testPropertyOriginalAmountWithoutMarkup()
    {
    }

    /**
     * Test attribute "settlementAmount"
     */
    public function testPropertySettlementAmount()
    {
    }

    /**
     * Test attribute "settlementCurrency"
     */
    public function testPropertySettlementCurrency()
    {
    }

    /**
     * Test attribute "settlementExchangeRate"
     */
    public function testPropertySettlementExchangeRate()
    {
    }
}
