<?php
/**
 * InvoicingV2InvoicesPost201ResponseInvoiceInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InvoicingV2InvoicesPost201ResponseInvoiceInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Contains all of the invoice-specific fields, such as the invoice number and due date.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoicingV2InvoicesPost201ResponseInvoiceInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InvoicingV2InvoicesPost201ResponseInvoiceInformation"
     */
    public function testInvoicingV2InvoicesPost201ResponseInvoiceInformation()
    {
    }

    /**
     * Test attribute "invoiceNumber"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "transactionReferenceNumber"
     */
    public function testPropertyTransactionReferenceNumber()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "dueDate"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "expirationDate"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "allowPartialPayments"
     */
    public function testPropertyAllowPartialPayments()
    {
    }

    /**
     * Test attribute "paymentLink"
     */
    public function testPropertyPaymentLink()
    {
    }

    /**
     * Test attribute "deliveryMode"
     */
    public function testPropertyDeliveryMode()
    {
    }

    /**
     * Test attribute "customLabels"
     */
    public function testPropertyCustomLabels()
    {
    }
}
