<?php
/**
 * InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformation"
     */
    public function testInvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformation()
    {
    }

    /**
     * Test attribute "merchantLogo"
     */
    public function testPropertyMerchantLogo()
    {
    }

    /**
     * Test attribute "merchantDisplayName"
     */
    public function testPropertyMerchantDisplayName()
    {
    }

    /**
     * Test attribute "customEmailMessage"
     */
    public function testPropertyCustomEmailMessage()
    {
    }

    /**
     * Test attribute "enableReminders"
     */
    public function testPropertyEnableReminders()
    {
    }

    /**
     * Test attribute "headerStyle"
     */
    public function testPropertyHeaderStyle()
    {
    }

    /**
     * Test attribute "deliveryLanguage"
     */
    public function testPropertyDeliveryLanguage()
    {
    }

    /**
     * Test attribute "defaultCurrencyCode"
     */
    public function testPropertyDefaultCurrencyCode()
    {
    }

    /**
     * Test attribute "payerAuthentication3DSVersion"
     */
    public function testPropertyPayerAuthentication3DSVersion()
    {
    }

    /**
     * Test attribute "showVatNumber"
     */
    public function testPropertyShowVatNumber()
    {
    }

    /**
     * Test attribute "vatRegistrationNumber"
     */
    public function testPropertyVatRegistrationNumber()
    {
    }

    /**
     * Test attribute "shipTo"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "phoneNumber"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "enableMerchantEmailNotifications"
     */
    public function testPropertyEnableMerchantEmailNotifications()
    {
    }

    /**
     * Test attribute "merchantEmail"
     */
    public function testPropertyMerchantEmail()
    {
    }

    /**
     * Test attribute "customLabels"
     */
    public function testPropertyCustomLabels()
    {
    }

    /**
     * Test attribute "customRedirectUrls"
     */
    public function testPropertyCustomRedirectUrls()
    {
    }
}
