<?php
/**
 * InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationCustomRedirectUrlsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationCustomRedirectUrlsTest Class Doc Comment
 *
 * @category    Class */
// * @description Object containing custom redirect URLs for different payment outcomes. Each property allows specifying a URL to which the customer will be redirected after a payment event.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationCustomRedirectUrlsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationCustomRedirectUrls"
     */
    public function testInvoicingV2InvoiceSettingsGet200ResponseInvoiceSettingsInformationCustomRedirectUrls()
    {
    }

    /**
     * Test attribute "paymentAccepted"
     */
    public function testPropertyPaymentAccepted()
    {
    }

    /**
     * Test attribute "paymentRejected"
     */
    public function testPropertyPaymentRejected()
    {
    }

    /**
     * Test attribute "paymentPending"
     */
    public function testPropertyPaymentPending()
    {
    }
}
