<?php
/**
 * Iplv2paymentlinksOrderInformationLineItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Iplv2paymentlinksOrderInformationLineItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description Line item from the order.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Iplv2paymentlinksOrderInformationLineItemsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Iplv2paymentlinksOrderInformationLineItems"
     */
    public function testIplv2paymentlinksOrderInformationLineItems()
    {
    }

    /**
     * Test attribute "productSku"
     */
    public function testPropertyProductSku()
    {
    }

    /**
     * Test attribute "productName"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "productDescription"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "discountAmount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "discountPercent"
     */
    public function testPropertyDiscountPercent()
    {
    }

    /**
     * Test attribute "taxAmount"
     */
    public function testPropertyTaxAmount()
    {
    }

    /**
     * Test attribute "taxRate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "totalAmount"
     */
    public function testPropertyTotalAmount()
    {
    }
}
