<?php
/**
 * LabelRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * LabelRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Label submission request for providing ground truth feedback on previously assessed transactions
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LabelRequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LabelRequest"
     */
    public function testLabelRequest()
    {
    }

    /**
     * Test attribute "actions"
     */
    public function testPropertyActions()
    {
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
    }

    /**
     * Test attribute "requestId"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "eventTime"
     */
    public function testPropertyEventTime()
    {
    }

    /**
     * Test attribute "transaction"
     */
    public function testPropertyTransaction()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }
}
