<?php
/**
 * ListAgentKeysResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * ListAgentKeysResponse200Test Class Doc Comment
 *
 * @category    Class */
// * @description Response for GET /icc/v1/agents/{agentId}/keys - agent info at top level with keys array
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListAgentKeysResponse200Test extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListAgentKeysResponse200"
     */
    public function testListAgentKeysResponse200()
    {
    }

    /**
     * Test attribute "agentId"
     */
    public function testPropertyAgentId()
    {
    }

    /**
     * Test attribute "agentName"
     */
    public function testPropertyAgentName()
    {
    }

    /**
     * Test attribute "keys"
     */
    public function testPropertyKeys()
    {
    }

    /**
     * Test attribute "pagination"
     */
    public function testPropertyPagination()
    {
    }
}
