<?php
/**
 * MerchantRegistrationResponse201Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * MerchantRegistrationResponse201Test Class Doc Comment
 *
 * @category    Class */
// * @description Response object for a registered merchant, including its associated encryption keys.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MerchantRegistrationResponse201Test extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantRegistrationResponse201"
     */
    public function testMerchantRegistrationResponse201()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "merchantName"
     */
    public function testPropertyMerchantName()
    {
    }

    /**
     * Test attribute "merchantUrl"
     */
    public function testPropertyMerchantUrl()
    {
    }

    /**
     * Test attribute "vmid"
     */
    public function testPropertyVmid()
    {
    }

    /**
     * Test attribute "cryptogramType"
     */
    public function testPropertyCryptogramType()
    {
    }

    /**
     * Test attribute "paymentPayloadType"
     */
    public function testPropertyPaymentPayloadType()
    {
    }

    /**
     * Test attribute "indicator"
     */
    public function testPropertyIndicator()
    {
    }

    /**
     * Test attribute "merchantMetadata"
     */
    public function testPropertyMerchantMetadata()
    {
    }

    /**
     * Test attribute "acceptanceRelationships"
     */
    public function testPropertyAcceptanceRelationships()
    {
    }

    /**
     * Test attribute "protocolInteractions"
     */
    public function testPropertyProtocolInteractions()
    {
    }

    /**
     * Test attribute "webIntegrations"
     */
    public function testPropertyWebIntegrations()
    {
    }

    /**
     * Test attribute "apiIntegrations"
     */
    public function testPropertyApiIntegrations()
    {
    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "keys"
     */
    public function testPropertyKeys()
    {
    }
}
