<?php
/**
 * MppCredentialsResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * MppCredentialsResponse200Test Class Doc Comment
 *
 * @category    Class */
// * @description MPP payment credentials response. The &#39;token&#39; field Contains the RSA-OAEP encrypted network token ciphertext. All other fields are display-only metadata.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MppCredentialsResponse200Test extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MppCredentialsResponse200"
     */
    public function testMppCredentialsResponse200()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }

    /**
     * Test attribute "lastFour"
     */
    public function testPropertyLastFour()
    {
    }

    /**
     * Test attribute "expirationMonth"
     */
    public function testPropertyExpirationMonth()
    {
    }

    /**
     * Test attribute "expirationYear"
     */
    public function testPropertyExpirationYear()
    {
    }

    /**
     * Test attribute "dynamicData"
     */
    public function testPropertyDynamicData()
    {
    }

    /**
     * Test attribute "eci"
     */
    public function testPropertyEci()
    {
    }

    /**
     * Test attribute "paymentAccountReference"
     */
    public function testPropertyPaymentAccountReference()
    {
    }
}
