<?php
/**
 * PaymentsProductsServiceFeeConfigurationInformationConfigurationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PaymentsProductsServiceFeeConfigurationInformationConfigurationsTest Class Doc Comment
 *
 * @category    Class */
// * @description PaymentsProductsServiceFeeConfigurationInformationConfigurations
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentsProductsServiceFeeConfigurationInformationConfigurationsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentsProductsServiceFeeConfigurationInformationConfigurations"
     */
    public function testPaymentsProductsServiceFeeConfigurationInformationConfigurations()
    {
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
    }

    /**
     * Test attribute "terminalId"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "merchantId"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "merchantInformation"
     */
    public function testPropertyMerchantInformation()
    {
    }

    /**
     * Test attribute "paymentInformation"
     */
    public function testPropertyPaymentInformation()
    {
    }
}
