<?php
/**
 * PblPaymentLinksAllGet200ResponsePurchaseInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PblPaymentLinksAllGet200ResponsePurchaseInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Contains link specific detail.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PblPaymentLinksAllGet200ResponsePurchaseInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PblPaymentLinksAllGet200ResponsePurchaseInformation"
     */
    public function testPblPaymentLinksAllGet200ResponsePurchaseInformation()
    {
    }

    /**
     * Test attribute "purchaseNumber"
     */
    public function testPropertyPurchaseNumber()
    {
    }

    /**
     * Test attribute "paymentLink"
     */
    public function testPropertyPaymentLink()
    {
    }
}
