<?php
/**
 * PostTokenizedCardRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PostTokenizedCardRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description PostTokenizedCardRequest
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostTokenizedCardRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostTokenizedCardRequest"
     */
    public function testPostTokenizedCardRequest()
    {
    }

    /**
     * Test attribute "accountReferenceId"
     */
    public function testPropertyAccountReferenceId()
    {
    }

    /**
     * Test attribute "consumerId"
     */
    public function testPropertyConsumerId()
    {
    }

    /**
     * Test attribute "createPanInstrumentIdentifier"
     */
    public function testPropertyCreatePanInstrumentIdentifier()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "card"
     */
    public function testPropertyCard()
    {
    }

    /**
     * Test attribute "passcode"
     */
    public function testPropertyPasscode()
    {
    }

    /**
     * Test attribute "billTo"
     */
    public function testPropertyBillTo()
    {
    }
}
