<?php
/**
 * PtsV2PaymentsPost201ResponseClearingInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PtsV2PaymentsPost201ResponseClearingInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsPost201ResponseClearingInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsPost201ResponseClearingInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsPost201ResponseClearingInformation"
     */
    public function testPtsV2PaymentsPost201ResponseClearingInformation()
    {
    }

    /**
     * Test attribute "authorizationCharacteristicsIndicator"
     */
    public function testPropertyAuthorizationCharacteristicsIndicator()
    {
    }

    /**
     * Test attribute "accountfundingSource"
     */
    public function testPropertyAccountfundingSource()
    {
    }

    /**
     * Test attribute "cardholderIdMethod"
     */
    public function testPropertyCardholderIdMethod()
    {
    }

    /**
     * Test attribute "marketSpecificDataIdentifier"
     */
    public function testPropertyMarketSpecificDataIdentifier()
    {
    }

    /**
     * Test attribute "posEntryMode"
     */
    public function testPropertyPosEntryMode()
    {
    }

    /**
     * Test attribute "electronicCommerceIndicator"
     */
    public function testPropertyElectronicCommerceIndicator()
    {
    }

    /**
     * Test attribute "spendQualifiedIndicator"
     */
    public function testPropertySpendQualifiedIndicator()
    {
    }

    /**
     * Test attribute "validationCode"
     */
    public function testPropertyValidationCode()
    {
    }
}
