<?php
/**
 * Ptsv1pullfundstransferProcessingInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ptsv1pullfundstransferProcessingInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv1pullfundstransferProcessingInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv1pullfundstransferProcessingInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ptsv1pullfundstransferProcessingInformation"
     */
    public function testPtsv1pullfundstransferProcessingInformation()
    {
    }

    /**
     * Test attribute "commerceIndicator"
     */
    public function testPropertyCommerceIndicator()
    {
    }

    /**
     * Test attribute "fundingOptions"
     */
    public function testPropertyFundingOptions()
    {
    }

    /**
     * Test attribute "recurringOptions"
     */
    public function testPropertyRecurringOptions()
    {
    }

    /**
     * Test attribute "businessApplicationId"
     */
    public function testPropertyBusinessApplicationId()
    {
    }

    /**
     * Test attribute "purposeOfPayment"
     */
    public function testPropertyPurposeOfPayment()
    {
    }

    /**
     * Test attribute "payoutsOptions"
     */
    public function testPropertyPayoutsOptions()
    {
    }

    /**
     * Test attribute "languageCode"
     */
    public function testPropertyLanguageCode()
    {
    }
}
