<?php
/**
 * Ptsv2paymentsidcapturesProcessingInformationJapanPaymentOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ptsv2paymentsidcapturesProcessingInformationJapanPaymentOptionsTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2paymentsidcapturesProcessingInformationJapanPaymentOptions
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsidcapturesProcessingInformationJapanPaymentOptionsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ptsv2paymentsidcapturesProcessingInformationJapanPaymentOptions"
     */
    public function testPtsv2paymentsidcapturesProcessingInformationJapanPaymentOptions()
    {
    }

    /**
     * Test attribute "paymentMethod"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "bonuses"
     */
    public function testPropertyBonuses()
    {
    }

    /**
     * Test attribute "installments"
     */
    public function testPropertyInstallments()
    {
    }

    /**
     * Test attribute "firstBillingMonth"
     */
    public function testPropertyFirstBillingMonth()
    {
    }

    /**
     * Test attribute "bonusAmount"
     */
    public function testPropertyBonusAmount()
    {
    }

    /**
     * Test attribute "bonusMonth"
     */
    public function testPropertyBonusMonth()
    {
    }

    /**
     * Test attribute "secondBonusAmount"
     */
    public function testPropertySecondBonusAmount()
    {
    }

    /**
     * Test attribute "secondBonusMonth"
     */
    public function testPropertySecondBonusMonth()
    {
    }
}
