<?php
/**
 * Ptsv2billingagreementsPaymentInformationBankTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ptsv2billingagreementsPaymentInformationBankTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2billingagreementsPaymentInformationBank
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2billingagreementsPaymentInformationBankTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ptsv2billingagreementsPaymentInformationBank"
     */
    public function testPtsv2billingagreementsPaymentInformationBank()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "swiftCode"
     */
    public function testPropertySwiftCode()
    {
    }

    /**
     * Test attribute "scheme"
     */
    public function testPropertyScheme()
    {
    }

    /**
     * Test attribute "accountAlias"
     */
    public function testPropertyAccountAlias()
    {
    }
}
