<?php
/**
 * PtsV2PaymentsRefundPost201ResponseOrderInformationAmountDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PtsV2PaymentsRefundPost201ResponseOrderInformationAmountDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsRefundPost201ResponseOrderInformationAmountDetails
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsRefundPost201ResponseOrderInformationAmountDetailsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsRefundPost201ResponseOrderInformationAmountDetails"
     */
    public function testPtsV2PaymentsRefundPost201ResponseOrderInformationAmountDetails()
    {
    }

    /**
     * Test attribute "cashbackAmount"
     */
    public function testPropertyCashbackAmount()
    {
    }

    /**
     * Test attribute "settlementAmount"
     */
    public function testPropertySettlementAmount()
    {
    }

    /**
     * Test attribute "settlementCurrency"
     */
    public function testPropertySettlementCurrency()
    {
    }

    /**
     * Test attribute "exchangeRate"
     */
    public function testPropertyExchangeRate()
    {
    }

    /**
     * Test attribute "foreignAmount"
     */
    public function testPropertyForeignAmount()
    {
    }

    /**
     * Test attribute "foreignCurrency"
     */
    public function testPropertyForeignCurrency()
    {
    }
}
