<?php
/**
 * Ptsv2paymentreferencesUserInterfaceColorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ptsv2paymentreferencesUserInterfaceColorTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2paymentreferencesUserInterfaceColor
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentreferencesUserInterfaceColorTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ptsv2paymentreferencesUserInterfaceColor"
     */
    public function testPtsv2paymentreferencesUserInterfaceColor()
    {
    }

    /**
     * Test attribute "border"
     */
    public function testPropertyBorder()
    {
    }

    /**
     * Test attribute "borderSelected"
     */
    public function testPropertyBorderSelected()
    {
    }

    /**
     * Test attribute "button"
     */
    public function testPropertyButton()
    {
    }

    /**
     * Test attribute "buttonText"
     */
    public function testPropertyButtonText()
    {
    }

    /**
     * Test attribute "checkbox"
     */
    public function testPropertyCheckbox()
    {
    }

    /**
     * Test attribute "checkboxCheckMark"
     */
    public function testPropertyCheckboxCheckMark()
    {
    }

    /**
     * Test attribute "header"
     */
    public function testPropertyHeader()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }
}
