<?php
/**
 * PullFundsRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PullFundsRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description PullFundsRequest
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PullFundsRequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PullFundsRequest"
     */
    public function testPullFundsRequest()
    {
    }

    /**
     * Test attribute "clientReferenceInformation"
     */
    public function testPropertyClientReferenceInformation()
    {
    }

    /**
     * Test attribute "orderInformation"
     */
    public function testPropertyOrderInformation()
    {
    }

    /**
     * Test attribute "processingInformation"
     */
    public function testPropertyProcessingInformation()
    {
    }

    /**
     * Test attribute "recipientInformation"
     */
    public function testPropertyRecipientInformation()
    {
    }

    /**
     * Test attribute "senderInformation"
     */
    public function testPropertySenderInformation()
    {
    }

    /**
     * Test attribute "buyerInformation"
     */
    public function testPropertyBuyerInformation()
    {
    }

    /**
     * Test attribute "aggregatorInformation"
     */
    public function testPropertyAggregatorInformation()
    {
    }

    /**
     * Test attribute "merchantInformation"
     */
    public function testPropertyMerchantInformation()
    {
    }
}
