<?php
/**
 * PushFunds201ResponseIssuerInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PushFunds201ResponseIssuerInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description PushFunds201ResponseIssuerInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PushFunds201ResponseIssuerInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PushFunds201ResponseIssuerInformation"
     */
    public function testPushFunds201ResponseIssuerInformation()
    {
    }

    /**
     * Test attribute "octDomesticParticipantIndicator"
     */
    public function testPropertyOctDomesticParticipantIndicator()
    {
    }

    /**
     * Test attribute "octCrossBorderParticipantIndicator"
     */
    public function testPropertyOctCrossBorderParticipantIndicator()
    {
    }

    /**
     * Test attribute "octMoneyTransferDomesticIndicator"
     */
    public function testPropertyOctMoneyTransferDomesticIndicator()
    {
    }

    /**
     * Test attribute "octMoneyTransferCrossBorderIndicator"
     */
    public function testPropertyOctMoneyTransferCrossBorderIndicator()
    {
    }

    /**
     * Test attribute "octMoneyTransferFastFundsDomesticIndicator"
     */
    public function testPropertyOctMoneyTransferFastFundsDomesticIndicator()
    {
    }

    /**
     * Test attribute "octMoneyTransferFastFundsCrossBorderIndicator"
     */
    public function testPropertyOctMoneyTransferFastFundsCrossBorderIndicator()
    {
    }

    /**
     * Test attribute "octMoneyTransferMerchantCountryRestricted"
     */
    public function testPropertyOctMoneyTransferMerchantCountryRestricted()
    {
    }

    /**
     * Test attribute "octNonMoneyTransferDomesticIndicator"
     */
    public function testPropertyOctNonMoneyTransferDomesticIndicator()
    {
    }

    /**
     * Test attribute "octNonMoneyTransferCrossBorderIndicator"
     */
    public function testPropertyOctNonMoneyTransferCrossBorderIndicator()
    {
    }

    /**
     * Test attribute "octNonMoneyTransferFastFundsDomesticIndicator"
     */
    public function testPropertyOctNonMoneyTransferFastFundsDomesticIndicator()
    {
    }

    /**
     * Test attribute "octNonMoneyTransferFastFundsCrossBorderIndicator"
     */
    public function testPropertyOctNonMoneyTransferFastFundsCrossBorderIndicator()
    {
    }

    /**
     * Test attribute "octOnlineGamblingDomesticIndicator"
     */
    public function testPropertyOctOnlineGamblingDomesticIndicator()
    {
    }

    /**
     * Test attribute "octOnlineGamblingCrossBorderIndicator"
     */
    public function testPropertyOctOnlineGamblingCrossBorderIndicator()
    {
    }

    /**
     * Test attribute "octOnlineGamblingFastFundsDomesticIndicator"
     */
    public function testPropertyOctOnlineGamblingFastFundsDomesticIndicator()
    {
    }

    /**
     * Test attribute "octOnlineGamblingFastFundsCrossBorderIndicator"
     */
    public function testPropertyOctOnlineGamblingFastFundsCrossBorderIndicator()
    {
    }
}
