<?php
/**
 * PushFundsTransferPaymentInformationCardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PushFundsTransferPaymentInformationCardTest Class Doc Comment
 *
 * @category    Class */
// * @description PushFundsTransferPaymentInformationCard
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PushFundsTransferPaymentInformationCardTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PushFundsTransferPaymentInformationCard"
     */
    public function testPushFundsTransferPaymentInformationCard()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "securityCode"
     */
    public function testPropertySecurityCode()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "expirationMonth"
     */
    public function testPropertyExpirationMonth()
    {
    }

    /**
     * Test attribute "expirationYear"
     */
    public function testPropertyExpirationYear()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "paymentInstrument"
     */
    public function testPropertyPaymentInstrument()
    {
    }

    /**
     * Test attribute "instrumentIdentifier"
     */
    public function testPropertyInstrumentIdentifier()
    {
    }
}
