<?php
/**
 * SAConfigServiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * SAConfigServiceTest Class Doc Comment
 *
 * @category    Class */
// * @description SAConfigService
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SAConfigServiceTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SAConfigService"
     */
    public function testSAConfigService()
    {
    }

    /**
     * Test attribute "decisionManagerVerboseEnabled"
     */
    public function testPropertyDecisionManagerVerboseEnabled()
    {
    }

    /**
     * Test attribute "declinedRetryLimit"
     */
    public function testPropertyDeclinedRetryLimit()
    {
    }

    /**
     * Test attribute "decisionManagerEnabled"
     */
    public function testPropertyDecisionManagerEnabled()
    {
    }

    /**
     * Test attribute "tokenizationEnabled"
     */
    public function testPropertyTokenizationEnabled()
    {
    }

    /**
     * Test attribute "reverseAuthOnAddressVerificationSystemFailure"
     */
    public function testPropertyReverseAuthOnAddressVerificationSystemFailure()
    {
    }

    /**
     * Test attribute "deviceFingerprintEnabled"
     */
    public function testPropertyDeviceFingerprintEnabled()
    {
    }

    /**
     * Test attribute "reverseAuthOnCardVerificationNumberFailure"
     */
    public function testPropertyReverseAuthOnCardVerificationNumberFailure()
    {
    }
}
