<?php
/**
 * SAConfigTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * SAConfigTest Class Doc Comment
 *
 * @category    Class */
// * @description SAConfig
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SAConfigTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SAConfig"
     */
    public function testSAConfig()
    {
    }

    /**
     * Test attribute "parentProfileId"
     */
    public function testPropertyParentProfileId()
    {
    }

    /**
     * Test attribute "contactInformation"
     */
    public function testPropertyContactInformation()
    {
    }

    /**
     * Test attribute "notifications"
     */
    public function testPropertyNotifications()
    {
    }

    /**
     * Test attribute "service"
     */
    public function testPropertyService()
    {
    }

    /**
     * Test attribute "paymentMethods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "checkout"
     */
    public function testPropertyCheckout()
    {
    }

    /**
     * Test attribute "paymentTypes"
     */
    public function testPropertyPaymentTypes()
    {
    }
}
