<?php
/**
 * TmsCardArtTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * TmsCardArtTest Class Doc Comment
 *
 * @category    Class */
// * @description Card art associated with the tokenized card.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TmsCardArtTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TmsCardArt"
     */
    public function testTmsCardArt()
    {
    }

    /**
     * Test attribute "foregroundColor"
     */
    public function testPropertyForegroundColor()
    {
    }

    /**
     * Test attribute "backgroundColor"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "labelColor"
     */
    public function testPropertyLabelColor()
    {
    }

    /**
     * Test attribute "combinedAsset"
     */
    public function testPropertyCombinedAsset()
    {
    }

    /**
     * Test attribute "brandLogoAsset"
     */
    public function testPropertyBrandLogoAsset()
    {
    }

    /**
     * Test attribute "issuerLogoAsset"
     */
    public function testPropertyIssuerLogoAsset()
    {
    }

    /**
     * Test attribute "iconAsset"
     */
    public function testPropertyIconAsset()
    {
    }
}
