<?php
/**
 * Tmsv2tokenizeTokenInformationCustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Tmsv2tokenizeTokenInformationCustomerTest Class Doc Comment
 *
 * @category    Class */
// * @description Tmsv2tokenizeTokenInformationCustomer
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Tmsv2tokenizeTokenInformationCustomerTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Tmsv2tokenizeTokenInformationCustomer"
     */
    public function testTmsv2tokenizeTokenInformationCustomer()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "objectInformation"
     */
    public function testPropertyObjectInformation()
    {
    }

    /**
     * Test attribute "buyerInformation"
     */
    public function testPropertyBuyerInformation()
    {
    }

    /**
     * Test attribute "clientReferenceInformation"
     */
    public function testPropertyClientReferenceInformation()
    {
    }

    /**
     * Test attribute "merchantDefinedInformation"
     */
    public function testPropertyMerchantDefinedInformation()
    {
    }

    /**
     * Test attribute "defaultPaymentInstrument"
     */
    public function testPropertyDefaultPaymentInstrument()
    {
    }

    /**
     * Test attribute "defaultShippingAddress"
     */
    public function testPropertyDefaultShippingAddress()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "embedded"
     */
    public function testPropertyEmbedded()
    {
    }
}
