<?php
/**
 * Tmsv3tokenstokenIdpaymentcredentialsDeviceInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Tmsv3tokenstokenIdpaymentcredentialsDeviceInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Tmsv3tokenstokenIdpaymentcredentialsDeviceInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Tmsv3tokenstokenIdpaymentcredentialsDeviceInformation"
     */
    public function testTmsv3tokenstokenIdpaymentcredentialsDeviceInformation()
    {
    }

    /**
     * Test attribute "platformType"
     */
    public function testPropertyPlatformType()
    {
    }

    /**
     * Test attribute "ipAddress"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "httpAcceptContent"
     */
    public function testPropertyHttpAcceptContent()
    {
    }

    /**
     * Test attribute "httpBrowserLanguage"
     */
    public function testPropertyHttpBrowserLanguage()
    {
    }

    /**
     * Test attribute "httpBrowserJavaEnabled"
     */
    public function testPropertyHttpBrowserJavaEnabled()
    {
    }

    /**
     * Test attribute "httpBrowserJavaScriptEnabled"
     */
    public function testPropertyHttpBrowserJavaScriptEnabled()
    {
    }

    /**
     * Test attribute "httpBrowserColorDepth"
     */
    public function testPropertyHttpBrowserColorDepth()
    {
    }

    /**
     * Test attribute "httpBrowserScreenHeight"
     */
    public function testPropertyHttpBrowserScreenHeight()
    {
    }

    /**
     * Test attribute "httpBrowserScreenWidth"
     */
    public function testPropertyHttpBrowserScreenWidth()
    {
    }

    /**
     * Test attribute "httpBrowserTimeDifference"
     */
    public function testPropertyHttpBrowserTimeDifference()
    {
    }

    /**
     * Test attribute "userAgentBrowserValue"
     */
    public function testPropertyUserAgentBrowserValue()
    {
    }
}
