<?php
/**
 * UcFeatureSubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * UcFeatureSubscriptionTest Class Doc Comment
 *
 * @category    Class */
// * @description UcFeatureSubscription
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UcFeatureSubscriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UcFeatureSubscription"
     */
    public function testUcFeatureSubscription()
    {
    }

    /**
     * Test attribute "pazeForUnifiedCheckout"
     */
    public function testPropertyPazeForUnifiedCheckout()
    {
    }

    /**
     * Test attribute "tokenManagement"
     */
    public function testPropertyTokenManagement()
    {
    }

    /**
     * Test attribute "payPal"
     */
    public function testPropertyPayPal()
    {
    }

    /**
     * Test attribute "venmo"
     */
    public function testPropertyVenmo()
    {
    }

    /**
     * Test attribute "applePay"
     */
    public function testPropertyApplePay()
    {
    }

    /**
     * Test attribute "googlePay"
     */
    public function testPropertyGooglePay()
    {
    }

    /**
     * Test attribute "tinkPayByBank"
     */
    public function testPropertyTinkPayByBank()
    {
    }

    /**
     * Test attribute "eCheck"
     */
    public function testPropertyECheck()
    {
    }

    /**
     * Test attribute "p24"
     */
    public function testPropertyP24()
    {
    }

    /**
     * Test attribute "myBank"
     */
    public function testPropertyMyBank()
    {
    }

    /**
     * Test attribute "konbini"
     */
    public function testPropertyKonbini()
    {
    }

    /**
     * Test attribute "dragonPay"
     */
    public function testPropertyDragonPay()
    {
    }

    /**
     * Test attribute "decisionManager"
     */
    public function testPropertyDecisionManager()
    {
    }

    /**
     * Test attribute "payerAuthentication"
     */
    public function testPropertyPayerAuthentication()
    {
    }

    /**
     * Test attribute "afterPay"
     */
    public function testPropertyAfterPay()
    {
    }

    /**
     * Test attribute "ideal"
     */
    public function testPropertyIdeal()
    {
    }

    /**
     * Test attribute "multibanco"
     */
    public function testPropertyMultibanco()
    {
    }

    /**
     * Test attribute "bancontact"
     */
    public function testPropertyBancontact()
    {
    }

    /**
     * Test attribute "clickToPay"
     */
    public function testPropertyClickToPay()
    {
    }

    /**
     * Test attribute "unifiedClickToPaySDK"
     */
    public function testPropertyUnifiedClickToPaySDK()
    {
    }

    /**
     * Test attribute "portfolioAccessofSensitiveData"
     */
    public function testPropertyPortfolioAccessofSensitiveData()
    {
    }
}
