<?php
/**
 * UcpCompleteCheckoutRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * UcpCompleteCheckoutRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description UCP checkout completion payload. If payment context was provided in an earlier Create or Update call, this body may be omitted. When included, &#x60;payment_data&#x60; is required.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UcpCompleteCheckoutRequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UcpCompleteCheckoutRequest"
     */
    public function testUcpCompleteCheckoutRequest()
    {
    }

    /**
     * Test attribute "paymentData"
     */
    public function testPropertyPaymentData()
    {
    }

    /**
     * Test attribute "riskSignals"
     */
    public function testPropertyRiskSignals()
    {
    }
}
