<?php
/**
 * Ucv1sessionsDataOrderInformationAmountDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsDataOrderInformationAmountDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description Ucv1sessionsDataOrderInformationAmountDetails
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsDataOrderInformationAmountDetailsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ucv1sessionsDataOrderInformationAmountDetails"
     */
    public function testUcv1sessionsDataOrderInformationAmountDetails()
    {
    }

    /**
     * Test attribute "totalAmount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "freightAmount"
     */
    public function testPropertyFreightAmount()
    {
    }

    /**
     * Test attribute "dutyAmount"
     */
    public function testPropertyDutyAmount()
    {
    }

    /**
     * Test attribute "discountAmount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "taxAppliedAfterDiscount"
     */
    public function testPropertyTaxAppliedAfterDiscount()
    {
    }

    /**
     * Test attribute "taxAppliedLevel"
     */
    public function testPropertyTaxAppliedLevel()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "surcharge"
     */
    public function testPropertySurcharge()
    {
    }

    /**
     * Test attribute "subTotalAmount"
     */
    public function testPropertySubTotalAmount()
    {
    }

    /**
     * Test attribute "serviceFeeAmount"
     */
    public function testPropertyServiceFeeAmount()
    {
    }

    /**
     * Test attribute "taxAmount"
     */
    public function testPropertyTaxAmount()
    {
    }

    /**
     * Test attribute "taxDetails"
     */
    public function testPropertyTaxDetails()
    {
    }
}
