<?php
/**
 * Ucv1sessionsDataProcessingInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsDataProcessingInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ucv1sessionsDataProcessingInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsDataProcessingInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ucv1sessionsDataProcessingInformation"
     */
    public function testUcv1sessionsDataProcessingInformation()
    {
    }

    /**
     * Test attribute "reconciliationId"
     */
    public function testPropertyReconciliationId()
    {
    }

    /**
     * Test attribute "purposeOfPayment"
     */
    public function testPropertyPurposeOfPayment()
    {
    }

    /**
     * Test attribute "authorizationOptions"
     */
    public function testPropertyAuthorizationOptions()
    {
    }

    /**
     * Test attribute "recurringOptions"
     */
    public function testPropertyRecurringOptions()
    {
    }

    /**
     * Test attribute "bankTransferOptions"
     */
    public function testPropertyBankTransferOptions()
    {
    }

    /**
     * Test attribute "businessApplicationId"
     */
    public function testPropertyBusinessApplicationId()
    {
    }

    /**
     * Test attribute "commerceIndicator"
     */
    public function testPropertyCommerceIndicator()
    {
    }

    /**
     * Test attribute "processingInstruction"
     */
    public function testPropertyProcessingInstruction()
    {
    }
}
