<?php
/**
 * Ucv1sessionsPaymentConfigurationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsPaymentConfigurationsTest Class Doc Comment
 *
 * @category    Class */
// * @description Allows per-transaction payment type configuration overrides.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsPaymentConfigurationsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ucv1sessionsPaymentConfigurations"
     */
    public function testUcv1sessionsPaymentConfigurations()
    {
    }

    /**
     * Test attribute "gOOGLEPAY"
     */
    public function testPropertyGOOGLEPAY()
    {
    }

    /**
     * Test attribute "cLICKTOPAY"
     */
    public function testPropertyCLICKTOPAY()
    {
    }

    /**
     * Test attribute "pAYPAL"
     */
    public function testPropertyPAYPAL()
    {
    }

    /**
     * Test attribute "tMSTOKEN"
     */
    public function testPropertyTMSTOKEN()
    {
    }
}
