<?php
/**
 * Ucv1sessionsAppearanceVariablesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsAppearanceVariablesTest Class Doc Comment
 *
 * @category    Class */
// * @description CSS appearance variables. All variables optional.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsAppearanceVariablesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ucv1sessionsAppearanceVariables"
     */
    public function testUcv1sessionsAppearanceVariables()
    {
    }

    /**
     * Test attribute "backgroundColor"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "textColor"
     */
    public function testPropertyTextColor()
    {
    }

    /**
     * Test attribute "headerBackground"
     */
    public function testPropertyHeaderBackground()
    {
    }

    /**
     * Test attribute "headerForeground"
     */
    public function testPropertyHeaderForeground()
    {
    }

    /**
     * Test attribute "headerAvatarBackgroundColor"
     */
    public function testPropertyHeaderAvatarBackgroundColor()
    {
    }

    /**
     * Test attribute "headerAvatarForegroundColor"
     */
    public function testPropertyHeaderAvatarForegroundColor()
    {
    }

    /**
     * Test attribute "inputBackground"
     */
    public function testPropertyInputBackground()
    {
    }

    /**
     * Test attribute "inputColor"
     */
    public function testPropertyInputColor()
    {
    }

    /**
     * Test attribute "inputPlaceholderColor"
     */
    public function testPropertyInputPlaceholderColor()
    {
    }

    /**
     * Test attribute "inputBorderColor"
     */
    public function testPropertyInputBorderColor()
    {
    }

    /**
     * Test attribute "inputBorderStyle"
     */
    public function testPropertyInputBorderStyle()
    {
    }

    /**
     * Test attribute "inputBorderRadius"
     */
    public function testPropertyInputBorderRadius()
    {
    }

    /**
     * Test attribute "inputHoverBackground"
     */
    public function testPropertyInputHoverBackground()
    {
    }

    /**
     * Test attribute "inputHoverColor"
     */
    public function testPropertyInputHoverColor()
    {
    }

    /**
     * Test attribute "inputHoverPlaceholderColor"
     */
    public function testPropertyInputHoverPlaceholderColor()
    {
    }

    /**
     * Test attribute "inputHoverBorderColor"
     */
    public function testPropertyInputHoverBorderColor()
    {
    }

    /**
     * Test attribute "inputHoverBorderStyle"
     */
    public function testPropertyInputHoverBorderStyle()
    {
    }

    /**
     * Test attribute "inputFocusedBackground"
     */
    public function testPropertyInputFocusedBackground()
    {
    }

    /**
     * Test attribute "inputFocusedColor"
     */
    public function testPropertyInputFocusedColor()
    {
    }

    /**
     * Test attribute "inputFocusedPlaceholderColor"
     */
    public function testPropertyInputFocusedPlaceholderColor()
    {
    }

    /**
     * Test attribute "inputFocusedBorderColor"
     */
    public function testPropertyInputFocusedBorderColor()
    {
    }

    /**
     * Test attribute "inputFocusedBorderStyle"
     */
    public function testPropertyInputFocusedBorderStyle()
    {
    }

    /**
     * Test attribute "inputActiveBackground"
     */
    public function testPropertyInputActiveBackground()
    {
    }

    /**
     * Test attribute "inputActiveColor"
     */
    public function testPropertyInputActiveColor()
    {
    }

    /**
     * Test attribute "inputActivePlaceholderColor"
     */
    public function testPropertyInputActivePlaceholderColor()
    {
    }

    /**
     * Test attribute "inputActiveBorderColor"
     */
    public function testPropertyInputActiveBorderColor()
    {
    }

    /**
     * Test attribute "inputActiveBorderStyle"
     */
    public function testPropertyInputActiveBorderStyle()
    {
    }

    /**
     * Test attribute "inputPressedBackground"
     */
    public function testPropertyInputPressedBackground()
    {
    }

    /**
     * Test attribute "inputPressedColor"
     */
    public function testPropertyInputPressedColor()
    {
    }

    /**
     * Test attribute "inputPressedPlaceholderColor"
     */
    public function testPropertyInputPressedPlaceholderColor()
    {
    }

    /**
     * Test attribute "inputPressedBorderColor"
     */
    public function testPropertyInputPressedBorderColor()
    {
    }

    /**
     * Test attribute "inputPressedBorderStyle"
     */
    public function testPropertyInputPressedBorderStyle()
    {
    }

    /**
     * Test attribute "inputErrorBackground"
     */
    public function testPropertyInputErrorBackground()
    {
    }

    /**
     * Test attribute "inputErrorColor"
     */
    public function testPropertyInputErrorColor()
    {
    }

    /**
     * Test attribute "inputErrorPlaceholderColor"
     */
    public function testPropertyInputErrorPlaceholderColor()
    {
    }

    /**
     * Test attribute "inputErrorBorderColor"
     */
    public function testPropertyInputErrorBorderColor()
    {
    }

    /**
     * Test attribute "inputErrorBorderStyle"
     */
    public function testPropertyInputErrorBorderStyle()
    {
    }

    /**
     * Test attribute "inputValidBackground"
     */
    public function testPropertyInputValidBackground()
    {
    }

    /**
     * Test attribute "inputValidColor"
     */
    public function testPropertyInputValidColor()
    {
    }

    /**
     * Test attribute "inputValidPlaceholderColor"
     */
    public function testPropertyInputValidPlaceholderColor()
    {
    }

    /**
     * Test attribute "inputValidBorderColor"
     */
    public function testPropertyInputValidBorderColor()
    {
    }

    /**
     * Test attribute "inputValidBorderStyle"
     */
    public function testPropertyInputValidBorderStyle()
    {
    }

    /**
     * Test attribute "buttonBackground"
     */
    public function testPropertyButtonBackground()
    {
    }

    /**
     * Test attribute "buttonForeground"
     */
    public function testPropertyButtonForeground()
    {
    }

    /**
     * Test attribute "buttonShape"
     */
    public function testPropertyButtonShape()
    {
    }

    /**
     * Test attribute "buttonBorderColor"
     */
    public function testPropertyButtonBorderColor()
    {
    }

    /**
     * Test attribute "buttonBorderStyle"
     */
    public function testPropertyButtonBorderStyle()
    {
    }

    /**
     * Test attribute "buttonBorderRadius"
     */
    public function testPropertyButtonBorderRadius()
    {
    }

    /**
     * Test attribute "buttonHoverBackground"
     */
    public function testPropertyButtonHoverBackground()
    {
    }

    /**
     * Test attribute "buttonHoverForeground"
     */
    public function testPropertyButtonHoverForeground()
    {
    }

    /**
     * Test attribute "buttonHoverBorderColor"
     */
    public function testPropertyButtonHoverBorderColor()
    {
    }

    /**
     * Test attribute "buttonHoverBorderStyle"
     */
    public function testPropertyButtonHoverBorderStyle()
    {
    }

    /**
     * Test attribute "buttonFocusBackground"
     */
    public function testPropertyButtonFocusBackground()
    {
    }

    /**
     * Test attribute "buttonFocusForeground"
     */
    public function testPropertyButtonFocusForeground()
    {
    }

    /**
     * Test attribute "buttonFocusBorderColor"
     */
    public function testPropertyButtonFocusBorderColor()
    {
    }

    /**
     * Test attribute "buttonActiveBackground"
     */
    public function testPropertyButtonActiveBackground()
    {
    }

    /**
     * Test attribute "buttonActiveForeground"
     */
    public function testPropertyButtonActiveForeground()
    {
    }

    /**
     * Test attribute "buttonActiveBorderColor"
     */
    public function testPropertyButtonActiveBorderColor()
    {
    }

    /**
     * Test attribute "buttonActiveBorderStyle"
     */
    public function testPropertyButtonActiveBorderStyle()
    {
    }

    /**
     * Test attribute "buttonDisabledBackground"
     */
    public function testPropertyButtonDisabledBackground()
    {
    }

    /**
     * Test attribute "buttonDisabledForeground"
     */
    public function testPropertyButtonDisabledForeground()
    {
    }

    /**
     * Test attribute "buttonDisabledBorderColor"
     */
    public function testPropertyButtonDisabledBorderColor()
    {
    }

    /**
     * Test attribute "fontFamily"
     */
    public function testPropertyFontFamily()
    {
    }

    /**
     * Test attribute "borderRadius"
     */
    public function testPropertyBorderRadius()
    {
    }

    /**
     * Test attribute "paymentSelectionBackground"
     */
    public function testPropertyPaymentSelectionBackground()
    {
    }
}
