<?php
/**
 * Ucv1sessionsDataOrderInformationLineItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsDataOrderInformationLineItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description Ucv1sessionsDataOrderInformationLineItems
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsDataOrderInformationLineItemsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ucv1sessionsDataOrderInformationLineItems"
     */
    public function testUcv1sessionsDataOrderInformationLineItems()
    {
    }

    /**
     * Test attribute "productCode"
     */
    public function testPropertyProductCode()
    {
    }

    /**
     * Test attribute "productName"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "productSku"
     */
    public function testPropertyProductSku()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "unitOfMeasure"
     */
    public function testPropertyUnitOfMeasure()
    {
    }

    /**
     * Test attribute "totalAmount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "taxRate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "shippingCountryCode"
     */
    public function testPropertyShippingCountryCode()
    {
    }

    /**
     * Test attribute "taxAmount"
     */
    public function testPropertyTaxAmount()
    {
    }

    /**
     * Test attribute "taxAppliedAfterDiscount"
     */
    public function testPropertyTaxAppliedAfterDiscount()
    {
    }

    /**
     * Test attribute "taxStatusIndicator"
     */
    public function testPropertyTaxStatusIndicator()
    {
    }

    /**
     * Test attribute "taxTypeCode"
     */
    public function testPropertyTaxTypeCode()
    {
    }

    /**
     * Test attribute "amountIncludesTax"
     */
    public function testPropertyAmountIncludesTax()
    {
    }

    /**
     * Test attribute "typeOfSupply"
     */
    public function testPropertyTypeOfSupply()
    {
    }

    /**
     * Test attribute "commodityCode"
     */
    public function testPropertyCommodityCode()
    {
    }

    /**
     * Test attribute "discountAmount"
     */
    public function testPropertyDiscountAmount()
    {
    }

    /**
     * Test attribute "discountApplied"
     */
    public function testPropertyDiscountApplied()
    {
    }

    /**
     * Test attribute "discountRate"
     */
    public function testPropertyDiscountRate()
    {
    }

    /**
     * Test attribute "invoiceNumber"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "taxDetails"
     */
    public function testPropertyTaxDetails()
    {
    }

    /**
     * Test attribute "fulfillmentType"
     */
    public function testPropertyFulfillmentType()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "weightIdentifier"
     */
    public function testPropertyWeightIdentifier()
    {
    }

    /**
     * Test attribute "weightUnit"
     */
    public function testPropertyWeightUnit()
    {
    }

    /**
     * Test attribute "referenceDataCode"
     */
    public function testPropertyReferenceDataCode()
    {
    }

    /**
     * Test attribute "referenceDataNumber"
     */
    public function testPropertyReferenceDataNumber()
    {
    }

    /**
     * Test attribute "unitTaxAmount"
     */
    public function testPropertyUnitTaxAmount()
    {
    }

    /**
     * Test attribute "productDescription"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "giftCardCurrency"
     */
    public function testPropertyGiftCardCurrency()
    {
    }

    /**
     * Test attribute "shippingDestinationTypes"
     */
    public function testPropertyShippingDestinationTypes()
    {
    }

    /**
     * Test attribute "gift"
     */
    public function testPropertyGift()
    {
    }

    /**
     * Test attribute "passenger"
     */
    public function testPropertyPassenger()
    {
    }
}
