<?php
/**
 * Ucv1sessionsCompleteMandateTmsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsCompleteMandateTmsTest Class Doc Comment
 *
 * @category    Class */
// * @description Configure Unified Checkout to create a TMS token at the end of the payment journey
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsCompleteMandateTmsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ucv1sessionsCompleteMandateTms"
     */
    public function testUcv1sessionsCompleteMandateTms()
    {
    }

    /**
     * Test attribute "tokenCreate"
     */
    public function testPropertyTokenCreate()
    {
    }

    /**
     * Test attribute "tokenTypes"
     */
    public function testPropertyTokenTypes()
    {
    }
}
