<?php
/**
 * Ucv1sessionsPaymentConfigurationsPAYPALTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ucv1sessionsPaymentConfigurationsPAYPALTest Class Doc Comment
 *
 * @category    Class */
// * @description Ucv1sessionsPaymentConfigurationsPAYPAL
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsPaymentConfigurationsPAYPALTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ucv1sessionsPaymentConfigurationsPAYPAL"
     */
    public function testUcv1sessionsPaymentConfigurationsPAYPAL()
    {
    }

    /**
     * Test attribute "vaultingEnabled"
     */
    public function testPropertyVaultingEnabled()
    {
    }

    /**
     * Test attribute "tokenizedPaymentMethod"
     */
    public function testPropertyTokenizedPaymentMethod()
    {
    }

    /**
     * Test attribute "industryType"
     */
    public function testPropertyIndustryType()
    {
    }
}
