<?php
/**
 * UnderwritingConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * UnderwritingConfigurationTest Class Doc Comment
 *
 * @category    Class */
// * @description Underwriting configuration containing the complete VMES (Visa Merchant Evaluation Service) payload for merchant risk evaluation.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnderwritingConfigurationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UnderwritingConfiguration"
     */
    public function testUnderwritingConfiguration()
    {
    }

    /**
     * Test attribute "clientReferenceInformation"
     */
    public function testPropertyClientReferenceInformation()
    {
    }

    /**
     * Test attribute "merchantApplication"
     */
    public function testPropertyMerchantApplication()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "metadataExternal"
     */
    public function testPropertyMetadataExternal()
    {
    }

    /**
     * Test attribute "organizationInformation"
     */
    public function testPropertyOrganizationInformation()
    {
    }

    /**
     * Test attribute "deviceInformation"
     */
    public function testPropertyDeviceInformation()
    {
    }

    /**
     * Test attribute "depositInformation"
     */
    public function testPropertyDepositInformation()
    {
    }

    /**
     * Test attribute "billingInformation"
     */
    public function testPropertyBillingInformation()
    {
    }

    /**
     * Test attribute "saleRepresentativeInformation"
     */
    public function testPropertySaleRepresentativeInformation()
    {
    }

    /**
     * Test attribute "fileAttachmentInformation"
     */
    public function testPropertyFileAttachmentInformation()
    {
    }
}
