<?php
/**
 * InstructionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CyberSource;

use \CyberSource\Configuration;
use \CyberSource\ApiClient;
use \CyberSource\ApiException;
use \CyberSource\ObjectSerializer;

/**
 * InstructionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstructionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelPurchaseIntent
     *
     * Cancel a purchase intent.
     *
     */
    public function testCancelPurchaseIntent()
    {
    }

    /**
     * Test case for confirmTransactionEvents
     *
     * Confirm transaction events.
     *
     */
    public function testConfirmTransactionEvents()
    {
    }

    /**
     * Test case for initiatePurchaseIntent
     *
     * Initiate a purchase intent.
     *
     */
    public function testInitiatePurchaseIntent()
    {
    }

    /**
     * Test case for retrievePaymentCredentials
     *
     * Retrieve payment credentials.
     *
     */
    public function testRetrievePaymentCredentials()
    {
    }

    /**
     * Test case for updatePurchaseIntent
     *
     * Update a purchase intent.
     *
     */
    public function testUpdatePurchaseIntent()
    {
    }
}
