<?php
/**
 * ManageWebhooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CyberSource;

use \CyberSource\Configuration;
use \CyberSource\ApiClient;
use \CyberSource\ApiException;
use \CyberSource\ObjectSerializer;

/**
 * ManageWebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ManageWebhooksApiTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteWebhookSubscription
     *
     * Delete a Webhook Subscription.
     *
     */
    public function testDeleteWebhookSubscription()
    {
    }

    /**
     * Test case for getWebhookSubscriptionById
     *
     * Get Details On a Single Webhook.
     *
     */
    public function testGetWebhookSubscriptionById()
    {
    }

    /**
     * Test case for getWebhookSubscriptionsByOrg
     *
     * Get Details On All Created Webhooks.
     *
     */
    public function testGetWebhookSubscriptionsByOrg()
    {
    }

    /**
     * Test case for notificationSubscriptionsV1WebhooksWebhookIdPost
     *
     * Test a Webhook Configuration.
     *
     */
    public function testNotificationSubscriptionsV1WebhooksWebhookIdPost()
    {
    }

    /**
     * Test case for notificationSubscriptionsV2WebhooksWebhookIdPatch
     *
     * Update a Webhook Subscription.
     *
     */
    public function testNotificationSubscriptionsV2WebhooksWebhookIdPatch()
    {
    }

    /**
     * Test case for notificationSubscriptionsV2WebhooksWebhookIdStatusPut
     *
     * Update a Webhook Status.
     *
     */
    public function testNotificationSubscriptionsV2WebhooksWebhookIdStatusPut()
    {
    }

    /**
     * Test case for saveAsymEgressKey
     *
     * Message Level Encryption.
     *
     */
    public function testSaveAsymEgressKey()
    {
    }
}
