<?php
/**
 * MerchantCapabilitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CyberSource;

use \CyberSource\Configuration;
use \CyberSource\ApiClient;
use \CyberSource\ApiException;
use \CyberSource\ObjectSerializer;

/**
 * MerchantCapabilitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MerchantCapabilitiesApiTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateMerchantKey
     *
     * Activate a merchant key.
     *
     */
    public function testActivateMerchantKey()
    {
    }

    /**
     * Test case for addMerchantKey
     *
     * Add a key to a merchant.
     *
     */
    public function testAddMerchantKey()
    {
    }

    /**
     * Test case for deactivateMerchantKey
     *
     * Deactivate a merchant key.
     *
     */
    public function testDeactivateMerchantKey()
    {
    }

    /**
     * Test case for getAllProducts
     *
     * Get All Products.
     *
     */
    public function testGetAllProducts()
    {
    }

    /**
     * Test case for getMerchant
     *
     * Get a merchant.
     *
     */
    public function testGetMerchant()
    {
    }

    /**
     * Test case for getMerchantKey
     *
     * Get a key by merchant and key ID.
     *
     */
    public function testGetMerchantKey()
    {
    }

    /**
     * Test case for getProduct
     *
     * Get Product by ID.
     *
     */
    public function testGetProduct()
    {
    }

    /**
     * Test case for ingestProductFeedJson
     *
     * Ingest Product Feed.
     *
     */
    public function testIngestProductFeedJson()
    {
    }

    /**
     * Test case for listMerchantKeys
     *
     * List keys for a merchant.
     *
     */
    public function testListMerchantKeys()
    {
    }

    /**
     * Test case for registerMerchant
     *
     * Register a merchant.
     *
     */
    public function testRegisterMerchant()
    {
    }

    /**
     * Test case for updateMerchant
     *
     * Update a merchant.
     *
     */
    public function testUpdateMerchant()
    {
    }

    /**
     * Test case for updateMerchantKey
     *
     * Update a merchant key.
     *
     */
    public function testUpdateMerchantKey()
    {
    }
}
