<?php
/**
 * MerchantDefinedFieldsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CyberSource;

use \CyberSource\Configuration;
use \CyberSource\ApiClient;
use \CyberSource\ApiException;
use \CyberSource\ObjectSerializer;

/**
 * MerchantDefinedFieldsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MerchantDefinedFieldsApiTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMerchantDefinedFieldDefinition
     *
     * Create merchant defined field for a given reference type.
     *
     */
    public function testCreateMerchantDefinedFieldDefinition()
    {
    }

    /**
     * Test case for createPblMerchantDefinedFieldDefinition
     *
     * Create a PayByLink merchant defined field for a given reference type.
     *
     */
    public function testCreatePblMerchantDefinedFieldDefinition()
    {
    }

    /**
     * Test case for deleteMerchantDefinedFieldsDefinitions
     *
     * Delete a MerchantDefinedField by ID.
     *
     */
    public function testDeleteMerchantDefinedFieldsDefinitions()
    {
    }

    /**
     * Test case for deletePblMerchantDefinedFieldsDefinitions
     *
     * Delete a PayByLink MerchantDefinedField by ID.
     *
     */
    public function testDeletePblMerchantDefinedFieldsDefinitions()
    {
    }

    /**
     * Test case for getMerchantDefinedFieldsDefinitions
     *
     * Get all merchant defined fields for a given reference type.
     *
     */
    public function testGetMerchantDefinedFieldsDefinitions()
    {
    }

    /**
     * Test case for getPblMerchantDefinedFieldsDefinitions
     *
     * Get all PayByLink merchant defined fields for a given reference type.
     *
     */
    public function testGetPblMerchantDefinedFieldsDefinitions()
    {
    }

    /**
     * Test case for putMerchantDefinedFieldsDefinitions
     *
     * Update a MerchantDefinedField by ID.
     *
     */
    public function testPutMerchantDefinedFieldsDefinitions()
    {
    }

    /**
     * Test case for putPblMerchantDefinedFieldsDefinitions
     *
     * Update a PayByLink MerchantDefinedField by ID.
     *
     */
    public function testPutPblMerchantDefinedFieldsDefinitions()
    {
    }
}
