<?php
/**
 * NetworkTokensApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CyberSource;

use \CyberSource\Configuration;
use \CyberSource\ApiClient;
use \CyberSource\ApiException;
use \CyberSource\ObjectSerializer;

/**
 * NetworkTokensApiTest Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworkTokensApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCardArtAsset
     *
     * Retrieve Card Art.
     *
     */
    public function testGetCardArtAsset()
    {
    }

    /**
     * Test case for getTokenizedCard
     *
     * Retrieve a Tokenized Card.
     *
     */
    public function testGetTokenizedCard()
    {
    }

    /**
     * Test case for postIssuerLifeCycleSimulation
     *
     * Simulate Issuer Life Cycle Management Events.
     *
     */
    public function testPostIssuerLifeCycleSimulation()
    {
    }

    /**
     * Test case for postTokenPaymentCredentials
     *
     * Generate Payment Credentials v2.
     *
     */
    public function testPostTokenPaymentCredentials()
    {
    }

    /**
     * Test case for postTokenPaymentCredentialsV3
     *
     * Generate Payment Credentials Latest Version v3.
     *
     */
    public function testPostTokenPaymentCredentialsV3()
    {
    }

    /**
     * Test case for postTokenizedCard
     *
     * Create a Tokenized Card.
     *
     */
    public function testPostTokenizedCard()
    {
    }

    /**
     * Test case for postTokenizedCardDelete
     *
     * Delete a Tokenized Card.
     *
     */
    public function testPostTokenizedCardDelete()
    {
    }
}
