<?php
/**
 * PaymentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CyberSource;

use \CyberSource\Configuration;
use \CyberSource\ApiClient;
use \CyberSource\ApiException;
use \CyberSource\ObjectSerializer;

/**
 * PaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentsApiTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createOrderRequest
     *
     * Create a Payment Order Request.
     *
     */
    public function testCreateOrderRequest()
    {
    }

    /**
     * Test case for createPayment
     *
     * Process a Payment.
     *
     */
    public function testCreatePayment()
    {
    }

    /**
     * Test case for createSessionRequest
     *
     * Create Alternative Payments Sessions Request.
     *
     */
    public function testCreateSessionRequest()
    {
    }

    /**
     * Test case for incrementAuth
     *
     * Increment an Authorization.
     *
     */
    public function testIncrementAuth()
    {
    }

    /**
     * Test case for refreshPaymentStatus
     *
     * Check a Payment Status.
     *
     */
    public function testRefreshPaymentStatus()
    {
    }

    /**
     * Test case for updateSessionRequest
     *
     * Update Alternative Payments Sessions Request.
     *
     */
    public function testUpdateSessionRequest()
    {
    }
}
